version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    groups:
      terraform-modules:
        patterns:
          - "*terraform-aws-modules/terraform-aws-ec2-instance*"
