version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    groups:
      terraform-modules:
        patterns:
          - "*terraform-module-ec2"
          - "*terraform-module-security-group"
